require:
  - rubocop-performance

inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rails.yml
    - config/rspec.yml

inherit_mode:
  merge:
    - Exclude

Style/HashSyntax:
  Exclude:
    - 'spec/factories/gross_income_summary_factory.rb'
    - 'spec/integration/ap_1367_spec.rb'
    - 'spec/integration/policy_disregards_spec.rb'
    - 'spec/integration/remarks_spec.rb'

# **** LEAVE FOR NOW ****
RSpec/AnyInstance:
  Exclude:
    - 'spec/requests/explicit_remarks_spec.rb'
    - 'spec/services/calculators/dependant_allowance_calculator_spec.rb'
    - 'spec/services/collators/childcare_collator_spec.rb'
    - 'spec/services/creators/explicit_remarks_creator_spec.rb'
    - 'spec/services/remark_generators/amount_variation_checker_spec.rb'
    - 'spec/services/remark_generators/frequency_checker_spec.rb'
    - 'spec/services/remark_generators/multi_benefit_checker_spec.rb'
    - 'spec/services/remark_generators/residual_balance_checker_spec.rb'
    - 'spec/requests/explicit_remarks_controller_spec.rb'

# **** LEAVE FOR NOW ****
RSpec/ContextWording:
  Enabled: false

# Swagger docs specs use `run_test!` method to dynamically generate
# a test and generate yaml. Rubocop does not recognize as a test.
RSpec/EmptyExampleGroup:
  Exclude:
    - spec/requests/swagger_docs/*

# **** LEAVE FOR NOW ****
RSpec/ExpectInHook:
  Exclude:
    - 'spec/models/bank_holiday_spec.rb'
    - 'spec/models/other_income_source_spec.rb'
    - 'spec/requests/applicants_spec.rb'
    - 'spec/requests/assessments_spec.rb'
    - 'spec/requests/outgoings_spec.rb'
    - 'spec/services/assessors/disposable_income_assessor_spec.rb'
    - 'spec/requests/outgoings_controller_spec.rb'
    - 'spec/requests/applicants_controller_spec.rb'

# ****
# **** Removing this will break specs.  It removes all the explicit subject declarations that it thinks aren't necessary, but doesn't always get it right.
# **** Better to leave the explicit subject declarations in.  May be fixed when all Rspec/NamedSubject offences are fixed.
# ****
RSpec/LeadingSubject:
  Enabled: false

# **** Leave these - they are historic migrations and no purpose is solved by changing them
Rails/BulkChangeTable:
  Exclude:
    - 'db/migrate/20200102101936_refactor_disposable_income_summaries.rb'
    - 'db/migrate/20200420132900_add_fields_to_gross_income_summary.rb'
    - 'db/migrate/20210412102115_add_version_proceeding_type_codes.rb'
    - 'db/migrate/20211110163830_add_gross_earned_income_to_gross_income_summary.rb'
    - 'db/migrate/20211117161654_update_fields_on_employment.rb'
    - 'db/migrate/20211207112406_add_additional_fields_to_summaries.rb'


# **** leave this - it is wrongly diagnosing an error
Rake/DuplicateTask:
  Exclude:
    - 'Rakefile'
